[package]
name = "stager"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking"]}
windows = { version = "0.48", features = [
   "Win32_System_Memory",
]}
