[package]
name = "PasswordRecovery"
version = "0.1.0"
edition = "2021"

[dependencies]
blake2 = "0.10.6"
md4 = "0.10.2"
md5 = "0.7.0"
sha2 = "0.10.8"
sha3 = "0.10.8"
streebog = "0.10.2"
tiger = "0.2.1"
whirlpool = "0.10.4"
